name: dasci
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=5.0.1
  - boost-cpp=1.69.0
  - bottleneck=1.3.6
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - comm=0.1.2
  - contourpy=1.0.7
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - flit-core=3.8.0
  - fontconfig=2.14.1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.6.0
  - grpc-cpp=1.46.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - intel-openmp=2022.1.0
  - ipykernel=6.20.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.1.3
  - jupyter_events=0.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.1.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=3.0
  - libabseil=20211102.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcurl=7.87.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markupsafe=2.1.2
  - matplotlib=3.6.3
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nb_conda_kernels=2.3.1
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.8
  - nbconvert-core=7.2.8
  - nbconvert-pandoc=7.2.8
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - ply=3.11
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py4j=0.10.9.5
  - pyarrow=8.0.0
  - pycparser=2.21
  - pygments=2.14.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.19.3
  - pyspark=3.3.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python_abi=3.10
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.1.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=66.1.1
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tbb=2021.6.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.8.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - utf8proc=2.6.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - pyqt5-sip==12.11.0
variables:
  BANK_ROOT_DIR: /home/willem/Documents/zakelijk/financieel/ING/transacties/
  JAVA_HOME: /home/willem/.sdkman/candidates/java/current
  MY_IBAN: NL79INGB0004951418
  SPARK_HOME: /home/willem/.sdkman/candidates/spark/current
  PATH: $JAVA_HOME/bin:/home/willem/anaconda3/envs/dasci/bin:/home/willem/anaconda3/condabin:$SPARK_HOME/bin:/home/willem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/willem/.local/share/JetBrains/Toolbox/scripts

  prefix: /home/willem/anaconda3/envs/dasci

